repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: Detect Secrets
  - repo: local
    hooks:
      - id: format
        name: Format
        entry: sh -c 'pnpm format'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: sh -c 'pnpm lint'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: typecheck
        name: Type Check
        entry: sh -c 'pnpm typecheck'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: Test
        name: Test
        entry: sh -c 'pnpm test:coverage'
        language: system
        pass_filenames: false
