packages:
  - .
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - "@getcommunity/config-prettier"
  - "@getcommunity/client-styleguides"
  - "@getcommunity/gc-validators"
  - "@getcommunity/strapi-blocks-solid-renderer"
  - vite@8.2.0
